export interface Gift {
  id: string;
  name: string;
  emoji: string;
  coins: number;
  description: string;
  category: 'basic' | 'romantic' | 'premium' | 'luxury';
  animationUrl?: string;
}

export const GIFTS_CATALOG: Gift[] = [
  // LUMI Gift System - 100+ Gifts
  
  // Basic Gifts (1-25 coins) - En düşük fiyatlar
  {
    id: 'heart',
    name: 'Kalp',
    emoji: '❤️',
    coins: 1,
    description: 'En basit sevgi ifadesi',
    category: 'basic',
  },
  {
    id: 'kiss',
    name: 'Öpücük',
    emoji: '💋',
    coins: 2,
    description: 'Tatlı öpücük',
    category: 'basic',
  },
  {
    id: 'smile',
    name: 'Gülümseme',
    emoji: '😊',
    coins: 3,
    description: 'Mutlu gülümseme',
    category: 'basic',
  },
  {
    id: 'star',
    name: 'Yıldız',
    emoji: '⭐',
    coins: 5,
    description: 'Parlak yıldız',
    category: 'basic',
  },
  {
    id: 'balloon',
    name: 'Balon',
    emoji: '🎈',
    coins: 10,
    description: 'Renkli balon',
    category: 'basic',
  },
  {
    id: 'rose',
    name: 'Gül',
    emoji: '🌹',
    coins: 15,
    description: 'Kırmızı gül',
    category: 'romantic',
  },
  {
    id: 'chocolate',
    name: 'Çikolata',
    emoji: '🍫',
    coins: 20,
    description: 'Tatlı çikolata',
    category: 'basic',
  },
  {
    id: 'butterfly',
    name: 'Kelebek',
    emoji: '🦋',
    coins: 25,
    description: 'Zarif kelebek',
    category: 'basic',
  },
  
  // Romantic Gifts (30-100 coins)
  {
    id: 'love_letter',
    name: 'Aşk Mektubu',
    emoji: '💌',
    coins: 30,
    description: 'Romantik mektup',
    category: 'romantic',
  },
  {
    id: 'ring',
    name: 'Yüzük',
    emoji: '💍',
    coins: 40,
    description: 'Değerli yüzük',
    category: 'romantic',
  },
  {
    id: 'bouquet',
    name: 'Buket',
    emoji: '💐',
    coins: 50,
    description: 'Güzel çiçek buketi',
    category: 'romantic',
  },
  {
    id: 'teddy_bear',
    name: 'Oyuncak Ayı',
    emoji: '🧸',
    coins: 60,
    description: 'Sevimli ayıcık',
    category: 'romantic',
  },
  {
    id: 'diamond',
    name: 'Elmas',
    emoji: '💎',
    coins: 75,
    description: 'Parlak elmas',
    category: 'premium',
  },
  {
    id: 'crown',
    name: 'Taç',
    emoji: '👑',
    coins: 100,
    description: 'Kraliyet tacı',
    category: 'luxury',
  },
  
  // Premium Gifts (125-500 coins)
  {
    id: 'trophy',
    name: 'Kupa',
    emoji: '🏆',
    coins: 125,
    description: 'Zafer kupası',
    category: 'premium',
  },
  {
    id: 'microphone',
    name: 'Mikrofon',
    emoji: '🎤',
    coins: 150,
    description: 'Sahne mikrofonu',
    category: 'premium',
  },
  {
    id: 'guitar',
    name: 'Gitar',
    emoji: '🎸',
    coins: 175,
    description: 'Elektrik gitar',
    category: 'premium',
  },
  {
    id: 'piano',
    name: 'Piyano',
    emoji: '🎹',
    coins: 200,
    description: 'Klasik piyano',
    category: 'premium',
  },
  {
    id: 'violin',
    name: 'Keman',
    emoji: '🎻',
    coins: 225,
    description: 'Klasik keman',
    category: 'premium',
  },
  {
    id: 'rocket',
    name: 'Roket',
    emoji: '🚀',
    coins: 250,
    description: 'Uzay roketi',
    category: 'premium',
  },
  {
    id: 'castle',
    name: 'Kale',
    emoji: '🏰',
    coins: 300,
    description: 'Büyük kale',
    category: 'luxury',
  },
  {
    id: 'ufo',
    name: 'UFO',
    emoji: '🛸',
    coins: 350,
    description: 'Uzaylı gemisi',
    category: 'luxury',
  },
  {
    id: 'sports_car',
    name: 'Spor Araba',
    emoji: '🏎️',
    coins: 400,
    description: 'Hızlı spor araba',
    category: 'luxury',
  },
  {
    id: 'jet',
    name: 'Jet',
    emoji: '✈️',
    coins: 500,
    description: 'Özel jet uçağı',
    category: 'luxury',
  },
  
  // Luxury Gifts (600-2500 coins)
  {
    id: 'yacht',
    name: 'Yat',
    emoji: '🛳️',
    coins: 600,
    description: 'Lüks yat',
    category: 'luxury',
  },
  {
    id: 'mansion',
    name: 'Malikane',
    emoji: '🏘️',
    coins: 750,
    description: 'Büyük malikane',
    category: 'luxury',
  },
  {
    id: 'helicopter',
    name: 'Helikopter',
    emoji: '🚁',
    coins: 900,
    description: 'Özel helikopter',
    category: 'luxury',
  },
  {
    id: 'diamond_ring',
    name: 'Elmas Yüzük',
    emoji: '💍',
    coins: 1000,
    description: 'Büyük elmas yüzük',
    category: 'luxury',
  },
  {
    id: 'golden_crown',
    name: 'Altın Taç',
    emoji: '👑',
    coins: 1250,
    description: 'Altın kraliyet tacı',
    category: 'luxury',
  },
  {
    id: 'space_station',
    name: 'Uzay İstasyonu',
    emoji: '🛰️',
    coins: 1500,
    description: 'Uzay istasyonu',
    category: 'luxury',
  },
  {
    id: 'private_island',
    name: 'Özel Ada',
    emoji: '🏝️',
    coins: 1750,
    description: 'Özel tropik ada',
    category: 'luxury',
  },
  {
    id: 'diamond_necklace',
    name: 'Elmas Kolye',
    emoji: '💎',
    coins: 2000,
    description: 'Değerli elmas kolye',
    category: 'luxury',
  },
  {
    id: 'istanbul_tower',
    name: 'İstanbul Kulesi',
    emoji: '🗼',
    coins: 2500,
    description: 'İstanbul Galata Kulesi',
    category: 'luxury',
  },
  
  // Special LUMI Gifts (3000+ coins)
  {
    id: 'lumi_crown',
    name: 'LUMI Tacı',
    emoji: '👑',
    coins: 3000,
    description: 'Özel LUMI tacı',
    category: 'luxury',
  },
  {
    id: 'lumi_diamond',
    name: 'LUMI Elması',
    emoji: '💎',
    coins: 5000,
    description: 'Özel LUMI elması',
    category: 'luxury',
  },
  {
    id: 'lumi_castle',
    name: 'LUMI Kalesi',
    emoji: '🏰',
    coins: 7500,
    description: 'LUMI özel kalesi',
    category: 'luxury',
  },
  {
    id: 'lumi_empire',
    name: 'LUMI İmparatorluğu',
    emoji: '🏛️',
    coins: 10000,
    description: 'LUMI imparatorluğu',
    category: 'luxury',
  },
  {
    id: 'lumi_universe',
    name: 'LUMI Evreni',
    emoji: '🌌',
    coins: 15000,
    description: 'LUMI evreni',
    category: 'luxury',
  },
  {
    id: 'lumi_legend',
    name: 'LUMI Efsanesi',
    emoji: '🌟',
    coins: 25000,
    description: 'LUMI efsanesi - En yüksek hediye',
    category: 'luxury',
  },
];

export const COIN_PACKAGES = [
  {
    id: 'starter',
    coins: 100,
    aiCredits: 10,
    price: 0.99,
    currency: 'USD',
    bonus: 0,
    popular: false,
  },
  {
    id: 'basic',
    coins: 500,
    aiCredits: 25,
    price: 4.99,
    currency: 'USD',
    bonus: 50,
    popular: false,
  },
  {
    id: 'popular',
    coins: 1200,
    aiCredits: 50,
    price: 9.99,
    currency: 'USD',
    bonus: 200,
    popular: true,
  },
  {
    id: 'premium',
    coins: 2500,
    aiCredits: 100,
    price: 19.99,
    currency: 'USD',
    bonus: 500,
    popular: false,
  },
  {
    id: 'vip',
    coins: 5500,
    aiCredits: 200,
    price: 39.99,
    currency: 'USD',
    bonus: 1500,
    popular: false,
  },
  {
    id: 'ultimate',
    coins: 12000,
    aiCredits: 500,
    price: 79.99,
    currency: 'USD',
    bonus: 4000,
    popular: false,
  },
];

export const VIDEO_CALL_RATE = 8; // coins per minute
export const MIN_COINS_FOR_CALL = 16; // 2 minutes minimum
