export const translations = {
  en: {
    // Auth
    welcomeBack: "Welcome back!",
    joinCommunity: "Join the community",
    signInToContinue: "Sign in to continue your journey",
    createAccountToStart: "Create your account to get started",
    displayName: "Display Name",
    email: "Email",
    password: "Password",
    phone: "Phone",
    phoneNumber: "Phone Number",
    signIn: "Sign In",
    signUp: "Sign Up",
    createAccount: "Create Account",
    pleaseWait: "Please wait...",
    dontHaveAccount: "Don't have an account? ",
    alreadyHaveAccount: "Already have an account? ",
    error: "Error",
    pleaseFillAllFields: "Please fill in all fields",
    authFailed: "Authentication failed. Please try again.",
    
    // Auth Methods
    chooseSignUpMethod: "Choose how to sign up",
    chooseHowToSignUp: "Choose your preferred method",
    signUpWithEmail: "Sign up with Email",
    signUpWithPhone: "Sign up with Phone",
    emailVerificationRequired: "Email verification required",
    smsVerificationRequired: "SMS verification required",
    continue: "Continue",
    back: "Back",
    
    // Verification
    verification: "Verification",
    enterVerificationCode: "Enter verification code",
    codeSentToEmail: "We sent a 6-digit code to {email}",
    codeSentToPhone: "We sent a 6-digit code to {phone}",
    verify: "Verify",
    resendCode: "Resend code",
    resendCodeIn: "Resend code in {seconds}s",
    verificationSent: "Verification code sent",
    checkYourEmail: "Please check your email",
    checkYourPhone: "Please check your phone",
    verificationFailed: "Verification failed. Please try again.",
    enterValidCode: "Please enter a valid 6-digit code",
    almostThere: "Almost there!",
    fillYourDetails: "Fill in your details",
    sendVerificationCode: "Send verification code",
    
    // Forgot Password
    forgotPassword: "Forgot Password?",
    forgotPasswordMessage: "We'll send you a reset link",
    
    // Navigation
    home: "Home",
    discover: "Discover",
    wallet: "Wallet",
    messages: "Messages",
    profile: "Profile",
    
    // Home
    liveNow: "Live Now",
    startVideoCall: "Start Video Call",
    findSomeone: "Find someone to chat with",
    goLive: "Go Live",
    seeAll: "See All",
    goodEvening: "Good evening",
    goodMorning: "Good morning",
    goodAfternoon: "Good afternoon",
    coins: "coins",
    level: "Level",
    followers: "Followers",
    noLiveStreams: "No live streams at the moment",
    
    // Wallet
    coinBalance: "Coin Balance",
    buyCoin: "Buy Coins",
    coinPackages: "Coin Packages",
    transactions: "Transactions",
    purchaseHistory: "Purchase History",
    
    // Video Call
    connecting: "Connecting...",
    searchingForPartner: "Searching for a partner...",
    callRate: "coins/min",
    endCall: "End Call",
    nextPartner: "Next Partner",
    reportUser: "Report User",
    
    // Gifts
    sendGift: "Send Gift",
    gifts: "Gifts",
    giftSent: "Gift sent!",
    selectGift: "Select a gift",
    
    // Messaging
    typeMessage: "Type a message...",
    sendMessage: "Send",
    newMessage: "New Message",
    chatWith: "Chat with {name}",
    online: "Online",
    offline: "Offline",
    typing: "typing...",
    searchMessages: "Search messages",
    noMessages: "No messages yet",
    startConversation: "Start a conversation",
    
    // Voice Rooms
    voiceRooms: "Voice Rooms",
    createRoom: "Create Room",
    joinRoom: "Join Room",
    leaveRoom: "Leave Room",
    roomFull: "Room is full",
    speakers: "Speakers",
    listeners: "Listeners",
    raiseHand: "Raise Hand",
    lowerHand: "Lower Hand",
    mute: "Mute",
    unmute: "Unmute",
    
    // Safety & Moderation
    safety: "Safety",
    report: "Report",
    block: "Block",
    unblock: "Unblock",
    reportReason: "Reason for report",
    inappropriateContent: "Inappropriate content",
    harassment: "Harassment",
    spam: "Spam",
    other: "Other",
    reportSubmitted: "Report submitted",
    userBlocked: "User blocked",
    
    // Translation
    autoTranslate: "Auto-translate",
    translationOn: "Translation on",
    translationOff: "Translation off",
    showOriginal: "Show original",
    
    // Country & Phone
    selectCountry: "Select Country",
    countryCode: "Country Code",
    phoneWithCountry: "Phone Number with Country Code",
    
    // Common
    cancel: "Cancel",
    confirm: "Confirm",
    save: "Save",
    settings: "Settings",
    settingsTitle: "Settings",
    language: "Language",
    loading: "Loading...",
    retry: "Retry",
    done: "Done",
    ok: "OK",
    edit: "Edit",
    delete: "Delete",
    share: "Share",
    copy: "Copy",
    copied: "Copied!",

    // Profile & Verification
    verificationCenter: "Verification Center",
    identityVerification: "Identity Verification",
    identityVerificationDesc: "Upload ID document",
    selfieVerification: "Selfie Verification",
    selfieVerificationDesc: "Take a selfie photo",
    verified: "Verified",
    pending: "Pending",
    notVerified: "Not Verified",
    agencyApplication: "Agency Application",
    manageAgency: "Manage agency",
    applicationPending: "Application pending",
    becomeVerifiedCreator: "Become a verified creator",
    active: "Active",
    applyNow: "Apply Now",
    hometown: "Hometown",
    notSet: "Not set",
    memberSince: "Member since",
    today: "Today",
    selectLanguage: "Select Language",
    doneText: "Done",
    changeAvatar: "Change Avatar",
    changeAvatarDesc: "Avatar upload functionality coming soon!",
    signOut: "Sign Out",
    signingOut: "Signing out…",
    signOutConfirmTitle: "Sign Out",
    signOutConfirmMessage: "Are you sure you want to sign out?",

    // Footer / Policies
    privacy: "Privacy",
    terms: "Terms",
    accountDeletion: "Account Deletion",
    accountCreationHelp: "Account Creation Help",

    // Chat & Search
    searchConversations: "Search conversations",
    noConversationsFound: "No conversations found",
    tryDifferentSearchTerm: "Try a different search term",
    noResults: "No results",
    tryDifferentKeyword: "Try a different keyword",
    searchMessagesPlaceholder: "Search messages...",
  },
  tr: {
    // Auth
    welcomeBack: "Tekrar hoş geldin!",
    joinCommunity: "Topluluğa katıl",
    signInToContinue: "Yolculuğuna devam etmek için giriş yap",
    createAccountToStart: "Başlamak için hesabını oluştur",
    displayName: "Görünen Ad",
    email: "E-posta",
    password: "Şifre",
    phone: "Telefon",
    phoneNumber: "Telefon Numarası",
    signIn: "Giriş Yap",
    signUp: "Kayıt Ol",
    createAccount: "Hesap Oluştur",
    pleaseWait: "Lütfen bekleyin...",
    dontHaveAccount: "Hesabın yok mu? ",
    alreadyHaveAccount: "Zaten hesabın var mı? ",
    error: "Hata",
    pleaseFillAllFields: "Lütfen tüm alanları doldurun",
    authFailed: "Kimlik doğrulama başarısız. Lütfen tekrar deneyin.",
    
    // Auth Methods
    chooseSignUpMethod: "Kayıt yöntemini seç",
    chooseHowToSignUp: "Tercih ettiğin yöntemi seç",
    signUpWithEmail: "E-posta ile kayıt ol",
    signUpWithPhone: "Telefon ile kayıt ol",
    emailVerificationRequired: "E-posta doğrulaması gerekli",
    smsVerificationRequired: "SMS doğrulaması gerekli",
    continue: "Devam Et",
    back: "Geri",
    
    // Verification
    verification: "Doğrulama",
    enterVerificationCode: "Doğrulama kodunu gir",
    codeSentToEmail: "{email} adresine 6 haneli kod gönderdik",
    codeSentToPhone: "{phone} numarasına 6 haneli kod gönderdik",
    verify: "Doğrula",
    resendCode: "Kodu tekrar gönder",
    resendCodeIn: "{seconds} saniye sonra tekrar gönder",
    verificationSent: "Doğrulama kodu gönderildi",
    checkYourEmail: "Lütfen e-postanı kontrol et",
    checkYourPhone: "Lütfen telefonunu kontrol et",
    verificationFailed: "Doğrulama başarısız. Lütfen tekrar deneyin.",
    enterValidCode: "Lütfen geçerli 6 haneli kod girin",
    almostThere: "Neredeyse bitti!",
    fillYourDetails: "Bilgilerini doldur",
    sendVerificationCode: "Doğrulama kodu gönder",
    
    // Forgot Password
    forgotPassword: "Şifremi Unuttum?",
    forgotPasswordMessage: "Sana sıfırlama linki göndereceğiz",
    
    // Navigation
    home: "Ana Sayfa",
    discover: "Keşfet",
    wallet: "Cüzdan",
    messages: "Mesajlar",
    profile: "Profil",
    
    // Home
    liveNow: "Şimdi Canlı",
    startVideoCall: "Görüntülü Arama Başlat",
    findSomeone: "Sohbet edecek birini bul",
    goLive: "Canlı Yayına Başla",
    seeAll: "Tümünü Gör",
    goodEvening: "İyi akşamlar",
    goodMorning: "Günaydın",
    goodAfternoon: "İyi günler",
    coins: "coin",
    level: "Seviye",
    followers: "Takipçi",
    noLiveStreams: "Şu anda canlı yayın yok",
    
    // Wallet
    coinBalance: "Coin Bakiyesi",
    buyCoin: "Coin Satın Al",
    coinPackages: "Coin Paketleri",
    transactions: "İşlemler",
    purchaseHistory: "Satın Alma Geçmişi",
    
    // Video Call
    connecting: "Bağlanıyor...",
    searchingForPartner: "Partner aranıyor...",
    callRate: "coin/dk",
    endCall: "Aramayı Bitir",
    nextPartner: "Sonraki Partner",
    reportUser: "Kullanıcıyı Bildir",
    
    // Gifts
    sendGift: "Hediye Gönder",
    gifts: "Hediyeler",
    giftSent: "Hediye gönderildi!",
    selectGift: "Hediye seç",
    
    // Messaging
    typeMessage: "Mesaj yaz...",
    sendMessage: "Gönder",
    newMessage: "Yeni Mesaj",
    chatWith: "{name} ile sohbet",
    online: "Çevrimiçi",
    offline: "Çevrimdışı",
    typing: "yazıyor...",
    searchMessages: "Mesajlarda ara",
    noMessages: "Henüz mesaj yok",
    startConversation: "Sohbet başlat",
    
    // Voice Rooms
    voiceRooms: "Sesli Odalar",
    createRoom: "Oda Oluştur",
    joinRoom: "Odaya Katıl",
    leaveRoom: "Odadan Ayrıl",
    roomFull: "Oda dolu",
    speakers: "Konuşmacılar",
    listeners: "Dinleyiciler",
    raiseHand: "El Kaldır",
    lowerHand: "Eli İndir",
    mute: "Sustur",
    unmute: "Sesi Aç",
    
    // Safety & Moderation
    safety: "Güvenlik",
    report: "Bildir",
    block: "Engelle",
    unblock: "Engeli Kaldır",
    reportReason: "Bildirme nedeni",
    inappropriateContent: "Uygunsuz içerik",
    harassment: "Taciz",
    spam: "Spam",
    other: "Diğer",
    reportSubmitted: "Bildirim gönderildi",
    userBlocked: "Kullanıcı engellendi",
    
    // Translation
    autoTranslate: "Otomatik çeviri",
    translationOn: "Çeviri açık",
    translationOff: "Çeviri kapalı",
    showOriginal: "Orijinali göster",
    
    // Country & Phone
    selectCountry: "Ülke Seç",
    countryCode: "Ülke Kodu",
    phoneWithCountry: "Ülke Kodu ile Telefon Numarası",
    
    // Common
    cancel: "İptal",
    confirm: "Onayla",
    save: "Kaydet",
    settings: "Ayarlar",
    settingsTitle: "Ayarlar",
    language: "Dil",
    loading: "Yükleniyor...",
    retry: "Tekrar Dene",
    done: "Tamam",
    ok: "Tamam",
    edit: "Düzenle",
    delete: "Sil",
    share: "Paylaş",
    copy: "Kopyala",
    copied: "Kopyalandı!",

    // Profile & Verification
    verificationCenter: "Doğrulama Merkezi",
    identityVerification: "Kimlik Doğrulama",
    identityVerificationDesc: "Kimlik belgesi yükle",
    selfieVerification: "Selfie Doğrulama",
    selfieVerificationDesc: "Selfie fotoğrafı çek",
    verified: "Doğrulandı",
    pending: "Beklemede",
    notVerified: "Doğrulanmadı",
    agencyApplication: "Ajans Başvurusu",
    manageAgency: "Ajansı yönet",
    applicationPending: "Başvuru beklemede",
    becomeVerifiedCreator: "Doğrulanmış içerik üreticisi ol",
    active: "Aktif",
    applyNow: "Şimdi Başvur",
    hometown: "Memleket",
    notSet: "Ayarlanmadı",
    memberSince: "Üyelik tarihi",
    today: "Bugün",
    selectLanguage: "Dil Seç",
    doneText: "Tamam",
    changeAvatar: "Avatar Değiştir",
    changeAvatarDesc: "Avatar yükleme özelliği yakında!",
    signOut: "Çıkış Yap",
    signingOut: "Çıkış yapılıyor…",
    signOutConfirmTitle: "Çıkış Yap",
    signOutConfirmMessage: "Çıkış yapmak istediğinizden emin misiniz?",

    // Footer / Policies
    privacy: "Gizlilik",
    terms: "Şartlar",
    accountDeletion: "Hesap Silme",
    accountCreationHelp: "Hesap Oluşturma Yardımı",

    // Chat & Search
    searchConversations: "Sohbetlerde ara",
    noConversationsFound: "Sohbet bulunamadı",
    tryDifferentSearchTerm: "Farklı bir arama terimi deneyin",
    noResults: "Sonuç yok",
    tryDifferentKeyword: "Farklı bir anahtar kelime deneyin",
    searchMessagesPlaceholder: "Mesajlarda ara...",
  },
  es: {
    // Auth
    welcomeBack: "¡Bienvenido de vuelta!",
    joinCommunity: "Únete a la comunidad",
    signInToContinue: "Inicia sesión para continuar tu viaje",
    createAccountToStart: "Crea tu cuenta para comenzar",
    displayName: "Nombre para mostrar",
    email: "Correo electrónico",
    password: "Contraseña",
    phone: "Teléfono",
    phoneNumber: "Número de teléfono",
    signIn: "Iniciar sesión",
    signUp: "Registrarse",
    createAccount: "Crear cuenta",
    pleaseWait: "Por favor espera...",
    dontHaveAccount: "¿No tienes una cuenta? ",
    alreadyHaveAccount: "¿Ya tienes una cuenta? ",
    error: "Error",
    pleaseFillAllFields: "Por favor completa todos los campos",
    authFailed: "Autenticación fallida. Por favor intenta de nuevo.",
    
    // Auth Methods
    chooseSignUpMethod: "Elige cómo registrarte",
    chooseHowToSignUp: "Elige tu método preferido",
    signUpWithEmail: "Registrarse con email",
    signUpWithPhone: "Registrarse con teléfono",
    emailVerificationRequired: "Verificación de email requerida",
    smsVerificationRequired: "Verificación SMS requerida",
    continue: "Continuar",
    back: "Atrás",
    
    // Verification
    verification: "Verificación",
    enterVerificationCode: "Ingresa el código de verificación",
    codeSentToEmail: "Enviamos un código de 6 dígitos a {email}",
    codeSentToPhone: "Enviamos un código de 6 dígitos a {phone}",
    verify: "Verificar",
    resendCode: "Reenviar código",
    resendCodeIn: "Reenviar código en {seconds}s",
    verificationSent: "Código de verificación enviado",
    checkYourEmail: "Por favor revisa tu email",
    checkYourPhone: "Por favor revisa tu teléfono",
    verificationFailed: "Verificación fallida. Por favor intenta de nuevo.",
    enterValidCode: "Por favor ingresa un código válido de 6 dígitos",
    almostThere: "¡Casi listo!",
    fillYourDetails: "Completa tus datos",
    sendVerificationCode: "Enviar código de verificación",
    
    // Forgot Password
    forgotPassword: "¿Olvidaste tu contraseña?",
    forgotPasswordMessage: "Te enviaremos un enlace de restablecimiento",
    
    // Navigation
    home: "Inicio",
    discover: "Descubrir",
    wallet: "Billetera",
    messages: "Mensajes",
    profile: "Perfil",
    
    // Home
    liveNow: "En vivo ahora",
    startVideoCall: "Iniciar videollamada",
    findSomeone: "Encuentra a alguien para chatear",
    goLive: "Transmitir en vivo",
    seeAll: "Ver todo",
    goodEvening: "Buenas noches",
    goodMorning: "Buenos días",
    goodAfternoon: "Buenas tardes",
    coins: "monedas",
    level: "Nivel",
    followers: "Seguidores",
    noLiveStreams: "No hay transmisiones en vivo en este momento",
    
    // Wallet
    coinBalance: "Balance de monedas",
    buyCoin: "Comprar monedas",
    coinPackages: "Paquetes de monedas",
    transactions: "Transacciones",
    purchaseHistory: "Historial de compras",
    
    // Video Call
    connecting: "Conectando...",
    searchingForPartner: "Buscando pareja...",
    callRate: "monedas/min",
    endCall: "Terminar llamada",
    nextPartner: "Siguiente pareja",
    reportUser: "Reportar usuario",
    
    // Gifts
    sendGift: "Enviar regalo",
    gifts: "Regalos",
    giftSent: "¡Regalo enviado!",
    selectGift: "Seleccionar regalo",
    
    // Messaging
    typeMessage: "Escribe un mensaje...",
    sendMessage: "Enviar",
    newMessage: "Nuevo mensaje",
    chatWith: "Chat con {name}",
    online: "En línea",
    offline: "Desconectado",
    typing: "escribiendo...",
    searchMessages: "Buscar mensajes",
    noMessages: "No hay mensajes aún",
    startConversation: "Iniciar conversación",
    
    // Voice Rooms
    voiceRooms: "Salas de voz",
    createRoom: "Crear sala",
    joinRoom: "Unirse a sala",
    leaveRoom: "Salir de sala",
    roomFull: "Sala llena",
    speakers: "Oradores",
    listeners: "Oyentes",
    raiseHand: "Levantar mano",
    lowerHand: "Bajar mano",
    mute: "Silenciar",
    unmute: "Activar sonido",
    
    // Safety & Moderation
    safety: "Seguridad",
    report: "Reportar",
    block: "Bloquear",
    unblock: "Desbloquear",
    reportReason: "Razón del reporte",
    inappropriateContent: "Contenido inapropiado",
    harassment: "Acoso",
    spam: "Spam",
    other: "Otro",
    reportSubmitted: "Reporte enviado",
    userBlocked: "Usuario bloqueado",
    
    // Translation
    autoTranslate: "Traducción automática",
    translationOn: "Traducción activada",
    translationOff: "Traducción desactivada",
    showOriginal: "Mostrar original",
    
    // Country & Phone
    selectCountry: "Seleccionar País",
    countryCode: "Código de País",
    phoneWithCountry: "Número de Teléfono con Código de País",
    
    // Common
    cancel: "Cancelar",
    confirm: "Confirmar",
    save: "Guardar",
    settings: "Configuración",
    settingsTitle: "Configuración",
    language: "Idioma",
    loading: "Cargando...",
    retry: "Reintentar",
    done: "Hecho",
    ok: "OK",
    edit: "Editar",
    delete: "Eliminar",
    share: "Compartir",
    copy: "Copiar",
    copied: "¡Copiado!",

    // Profile & Verification
    verificationCenter: "Centro de verificación",
    identityVerification: "Verificación de identidad",
    identityVerificationDesc: "Subir documento de identidad",
    selfieVerification: "Verificación de selfie",
    selfieVerificationDesc: "Tomar foto selfie",
    verified: "Verificado",
    pending: "Pendiente",
    notVerified: "No verificado",
    agencyApplication: "Solicitud de agencia",
    manageAgency: "Administrar agencia",
    applicationPending: "Solicitud pendiente",
    becomeVerifiedCreator: "Conviértete en creador verificado",
    active: "Activo",
    applyNow: "Aplicar ahora",
    hometown: "Ciudad natal",
    notSet: "No establecido",
    memberSince: "Miembro desde",
    today: "Hoy",
    selectLanguage: "Seleccionar idioma",
    doneText: "Hecho",
    changeAvatar: "Cambiar avatar",
    changeAvatarDesc: "¡Función de carga de avatar próximamente!",
    signOut: "Cerrar sesión",
    signingOut: "Cerrando sesión…",
    signOutConfirmTitle: "Cerrar sesión",
    signOutConfirmMessage: "¿Estás seguro de que quieres cerrar sesión?",

    // Footer / Policies
    privacy: "Privacidad",
    terms: "Términos",
    accountDeletion: "Eliminación de cuenta",
    accountCreationHelp: "Ayuda para crear cuenta",

    // Chat & Search
    searchConversations: "Buscar conversaciones",
    noConversationsFound: "No se encontraron conversaciones",
    tryDifferentSearchTerm: "Intenta con un término diferente",
    noResults: "Sin resultados",
    tryDifferentKeyword: "Intenta con una palabra clave diferente",
    searchMessagesPlaceholder: "Buscar mensajes...",
  },
  tl: {
    // Auth
    welcomeBack: "Maligayang pagbabalik!",
    joinCommunity: "Sumali sa komunidad",
    signInToContinue: "Mag-sign in upang ipagpatuloy ang inyong paglalakbay",
    createAccountToStart: "Gumawa ng account upang magsimula",
    displayName: "Display Name",
    email: "Email",
    password: "Password",
    phone: "Telepono",
    phoneNumber: "Numero ng Telepono",
    signIn: "Mag-sign In",
    signUp: "Mag-sign Up",
    createAccount: "Gumawa ng Account",
    pleaseWait: "Pakihintay...",
    dontHaveAccount: "Walang account? ",
    alreadyHaveAccount: "May account na? ",
    error: "Error",
    pleaseFillAllFields: "Pakipunan ang lahat ng fields",
    authFailed: "Hindi nagtagumpay ang authentication. Subukan ulit.",
    
    // Auth Methods
    chooseSignUpMethod: "Piliin kung paano mag-sign up",
    chooseHowToSignUp: "Piliin ang gusto mong paraan",
    signUpWithEmail: "Mag-sign up gamit ang Email",
    signUpWithPhone: "Mag-sign up gamit ang Telepono",
    emailVerificationRequired: "Kailangan ng email verification",
    smsVerificationRequired: "Kailangan ng SMS verification",
    continue: "Magpatuloy",
    back: "Bumalik",
    
    // Verification
    verification: "Verification",
    enterVerificationCode: "Ilagay ang verification code",
    codeSentToEmail: "Nagpadala kami ng 6-digit code sa {email}",
    codeSentToPhone: "Nagpadala kami ng 6-digit code sa {phone}",
    verify: "I-verify",
    resendCode: "Ipadala ulit ang code",
    resendCodeIn: "Ipadala ulit ang code sa {seconds}s",
    verificationSent: "Napadala na ang verification code",
    checkYourEmail: "Pakitingnan ang inyong email",
    checkYourPhone: "Pakitingnan ang inyong telepono",
    verificationFailed: "Hindi nagtagumpay ang verification. Subukan ulit.",
    enterValidCode: "Pakitype ang tamang 6-digit code",
    almostThere: "Malapit na!",
    fillYourDetails: "Punan ang inyong mga detalye",
    sendVerificationCode: "Ipadala ang verification code",
    
    // Forgot Password
    forgotPassword: "Nakalimutan ang Password?",
    forgotPasswordMessage: "Magpapadala kami ng reset link",
    
    // Navigation
    home: "Home",
    discover: "Tuklasin",
    wallet: "Wallet",
    messages: "Mga Mensahe",
    profile: "Profile",
    
    // Home
    liveNow: "Live Ngayon",
    startVideoCall: "Simulan ang Video Call",
    findSomeone: "Maghanap ng makakausap",
    goLive: "Mag-live",
    seeAll: "Tingnan Lahat",
    goodEvening: "Magandang gabi",
    goodMorning: "Magandang umaga",
    goodAfternoon: "Magandang hapon",
    coins: "coins",
    level: "Level",
    followers: "Mga Follower",
    noLiveStreams: "Walang live streams sa ngayon",
    
    // Wallet
    coinBalance: "Coin Balance",
    buyCoin: "Bumili ng Coins",
    coinPackages: "Mga Coin Package",
    transactions: "Mga Transaksyon",
    purchaseHistory: "Kasaysayan ng Pagbili",
    
    // Video Call
    connecting: "Kumukonekta...",
    searchingForPartner: "Naghahanap ng partner...",
    callRate: "coins/min",
    endCall: "Tapusin ang Tawag",
    nextPartner: "Susunod na Partner",
    reportUser: "I-report ang User",
    
    // Gifts
    sendGift: "Magpadala ng Regalo",
    gifts: "Mga Regalo",
    giftSent: "Napadala ang regalo!",
    selectGift: "Pumili ng regalo",
    
    // Messaging
    typeMessage: "Mag-type ng mensahe...",
    sendMessage: "Ipadala",
    newMessage: "Bagong Mensahe",
    chatWith: "Chat kay {name}",
    online: "Online",
    offline: "Offline",
    typing: "tumatype...",
    searchMessages: "Maghanap ng mensahe",
    noMessages: "Walang mensahe pa",
    startConversation: "Magsimula ng usapan",
    
    // Voice Rooms
    voiceRooms: "Mga Voice Room",
    createRoom: "Gumawa ng Room",
    joinRoom: "Sumali sa Room",
    leaveRoom: "Umalis sa Room",
    roomFull: "Puno na ang room",
    speakers: "Mga Nagsasalita",
    listeners: "Mga Nakikinig",
    raiseHand: "Itaas ang Kamay",
    lowerHand: "Ibaba ang Kamay",
    mute: "I-mute",
    unmute: "I-unmute",
    
    // Safety & Moderation
    safety: "Kaligtasan",
    report: "I-report",
    block: "I-block",
    unblock: "I-unblock",
    reportReason: "Dahilan ng pag-report",
    inappropriateContent: "Hindi angkop na content",
    harassment: "Pang-aabuso",
    spam: "Spam",
    other: "Iba pa",
    reportSubmitted: "Naisumite ang report",
    userBlocked: "Na-block ang user",
    
    // Translation
    autoTranslate: "Auto-translate",
    translationOn: "Naka-on ang translation",
    translationOff: "Naka-off ang translation",
    showOriginal: "Ipakita ang orihinal",
    
    // Country & Phone
    selectCountry: "Piliin ang Bansa",
    countryCode: "Country Code",
    phoneWithCountry: "Phone Number na may Country Code",
    
    // Common
    cancel: "Kanselahin",
    confirm: "Kumpirmahin",
    save: "I-save",
    settings: "Mga Setting",
    settingsTitle: "Mga Setting",
    language: "Wika",
    loading: "Nag-lo-load...",
    retry: "Subukan Ulit",
    done: "Tapos na",
    ok: "OK",
    edit: "I-edit",
    delete: "Tanggalin",
    share: "I-share",
    copy: "Kopyahin",
    copied: "Nakopya!",

    // Profile & Verification
    verificationCenter: "Verification Center",
    identityVerification: "Identity Verification",
    identityVerificationDesc: "Mag-upload ng ID document",
    selfieVerification: "Selfie Verification",
    selfieVerificationDesc: "Kumuha ng selfie photo",
    verified: "Verified",
    pending: "Pending",
    notVerified: "Hindi Verified",
    agencyApplication: "Agency Application",
    manageAgency: "Pamahalaan ang agency",
    applicationPending: "Pending ang application",
    becomeVerifiedCreator: "Maging verified creator",
    active: "Active",
    applyNow: "Mag-apply Ngayon",
    hometown: "Hometown",
    notSet: "Hindi nakatakda",
    memberSince: "Miyembro simula",
    today: "Ngayon",
    selectLanguage: "Pumili ng Wika",
    doneText: "Tapos na",
    changeAvatar: "Palitan ang Avatar",
    changeAvatarDesc: "Malapit nang dumating ang avatar upload!",
    signOut: "Mag-sign Out",
    signingOut: "Nag-si-sign out…",
    signOutConfirmTitle: "Mag-sign Out",
    signOutConfirmMessage: "Sigurado ka bang gusto mong mag-sign out?",

    // Footer / Policies
    privacy: "Privacy",
    terms: "Mga Tuntunin",
    accountDeletion: "Pagtanggal ng Account",
    accountCreationHelp: "Tulong sa Paggawa ng Account",

    // Chat & Search
    searchConversations: "Maghanap ng mga usapan",
    noConversationsFound: "Walang nahanap na usapan",
    tryDifferentSearchTerm: "Subukan ang ibang search term",
    noResults: "Walang resulta",
    tryDifferentKeyword: "Subukan ang ibang keyword",
    searchMessagesPlaceholder: "Maghanap ng mensahe...",
  },
};

export type Language = keyof typeof translations;
export type TranslationKey = keyof typeof translations.en;

export const supportedLanguages: { code: Language; name: string; flag: string }[] = [
  { code: 'en', name: 'English', flag: '🇺🇸' },
  { code: 'tr', name: 'Türkçe', flag: '🇹🇷' },
  { code: 'es', name: 'Español', flag: '🇪🇸' },
  { code: 'tl', name: 'Filipino', flag: '🇵🇭' },
];
