name: Auto Push to GitHub (Disabled)

on:
  workflow_dispatch:

jobs:
  auto-push:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: |
        rm -f package-lock.json
        npm install --legacy-peer-deps
      
    - name: Run tests
      run: npm run lint
      
    - name: Build project
      run: npm run build:web
      
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/main'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist
